### ISSUE TITLE
visible text upon background

### ISSUE THREAD

**Issue by EHMilon** [KatsuteDev/Background#159]
### Feature

This is best background changing extension in VS Code marketplace. But here are some issues i found.
if i set a background, text or code color getting change that cause some visibility issue because text background also get change. If there any way to without changing the background of text that will help to focus on coding.
In setting option there is a option, **Background: Use Window Options for All Backgrounds**. if enable this option background are not clearly displayed on editor and if change the blur and opacity of the background image doesn't work anything.
**So, my humble request to make an option that will not change the background of text and background blur and opacity is editable.** 

### Reason

**If the background doesn't impact the text color then it will help to focus coding.**

**Comment by Katsute** [comment]
> if i set a background, text or code color getting change that cause some visibility issue because text background also get change.

This is not currently possible due to how the background is installed, refer to https://github.com/KatsuteDev/Background/issues/75#issuecomment-1347698520; using the **`renderContentAboveBackground`** may fix this issue only in some cases.

> In setting option there is a option, **Background: Use Window Options for All Backgrounds**. if enable this option background are not clearly displayed on editor and if change the blur and opacity of the background image doesn't work anything.

This feature only changes the blur/opacity settings for the backgrounds, this does not include the images, images need to be selected separately for window/editor/panel/sidebar.

Note that blur/opacity is applied to the **background image** and not the interface/code.
