### ISSUE TITLE
Background for VS Code Profiles

### ISSUE THREAD

**Issue by m3koenig** [KatsuteDev/Background#194]
### Feature

I want to set different designs for different [VS Code Profiles](https://code.visualstudio.com/docs/editor/profiles).
I could not find any solution and would like this feature well! 

### Reason

It would be helpfull to use this as a profile identifier. Like an logo from the customers etc.

**Comment by Katsute** [comment]
This extension works by modifying the VSCode installation itself, it is not possible to 'see' different backgrounds every time you switch a profile since all profiles share the same base installation.

You can save separate background sets per profile, however the background itself can only change whenever you run the `Install` command.

**Comment by m3koenig** [comment]
mmh okay. I understand.
Is there a way for a relative Path? (I could not find).
So every "Project"/"Folder" could had its own BG Files.
I understand to use the `Install` command after I opend the project.

Or, did I get this right, is not possible because its the VSCode installation itself aswell?

**Comment by Katsute** [comment]
Currently being tracked as #193, would still require an install anytime you want a change.
