### ISSUE TITLE
Use HTTPS (address remains unchanged, content is updated regularly), and set background.backgroundChangeTime. The latest image will not be used for each background image switch

### ISSUE THREAD

**Issue by dingwd** [KatsuteDev/Background#248]
### Operating System

Windows 11

### VSCode Version

1.84.2

### Extension Version

2.8.3

### Issue

Use HTTPS (address remains unchanged, content is updated regularly), and set background.backgroundChangeTime. The latest image will not be used for each background image switch

### Settings

```json
{
    "background.windowBackgrounds": [
        "https://-.cn/-.jpeg"
    ],
    "background.backgroundAlignment": [
        "Center Center",
        "Center Center",
        "Center Center",
        "Center Center"
    ],
    "workbench.settings.applyToAllProfiles": [
        "background.backgroundChangeTime"
    ],
    "background.backgroundChangeTime": [
        10,
        0,
        0,
        0
    ]
}
```

### How to replicate

Install the plugin, follow instructions

**Comment by Katsute** [comment]
The background doesn't change because VSCode is using the cached image. Any time it sees an image url it has already used before it will pull the image from memory, rather than fetching again.

There are workarounds for this to force the image to not cache, however it would cause a memory leak and would slow down VSCode over time.

Is an alternative, download all the image files to disk and load the backgrounds from a local folder.
