### ISSUE TITLE
WSL: Not working

### ISSUE THREAD

**Issue by furtimx** [KatsuteDev/Background#27]
### Operating System

Windows 10

### VSCode Version

v1.70.0

### Extension Version

v1.1.0

### Issue

Showing an error "Failed to find 'bootstrap-window.js'" after choosing a file and reloading

### How to replicate

1. Install extension on a remote WSL
2. Choose a file inside the linux distro
3. Install and Reload the extension

**Comment by Katsute** [comment]
Unfortunately the file that we use to inject the css `bootstrap-window.js` does not exist on the WSL installation of VSCode. When you use remote WSL on Windows it will open a new window using your local installation of VSCode, while the backend (i.e. extensions) will run in the linux directory. Because of this separation the WSL cannot see or modify the file that handles the css.

This separation only means you **cannot make changes**.

If you choose a file and make changes in the main VSCode window, install, then open a remote WSL, you will see the background on the WSL window.
