### ISSUE TITLE
Scroll repeating images

### ISSUE THREAD

**Issue by VulumeCode** [KatsuteDev/Background#273]
### Feature

There should be an option to scroll the image with the editor, so text stays aligned with the image

### Reason

I want to use a repeating paper-like texture. The text in my editor should scroll with the paper it's "written on".

**Comment by Katsute** [comment]
Unfortunately there is no way to add this feature because VSCode does not actually use scrollable containers. The editor only loads the lines you can see and adds/removes them from the top/bottom of the screen as you 'scroll', rather than loading an entire code file and actually scrolling through it.
