### ISSUE TITLE
Config option for background.renderContentAboveBackground (set to true by default)

### ISSUE THREAD

**Issue by nathanchenseanwalter** [KatsuteDev/Background#294]
### Feature

background.renderContentAboveBackground is true by default and has an option in config

### Reason

Just one more option, and would work in more cases

**Comment by Katsute** [comment]
The `renderContentAboveBackground` is not set to true by default in order to keep our behavior the same as other background extensions. Switching this to true would also impact an estimated 80,000 users which may not want this behavior by default.

Adding these options to the menu would also create unnecessary clutter and take much longer than if you would use the native VSCode configuration. The main purpose of the background menu is to simplify the setting of images and not the optional settings that users can toggle.
