### ISSUE TITLE
[Feat] Option to configure how images are selected

### ISSUE THREAD

**Issue by daephx** [KatsuteDev/Background#59]
### Feature

Allow user to change aspect of the image selector instead of purely by random.
My idea for this include options such as:
- `random`: Unchanged from default functionality
- `unique`: Randomly enumerate without repeating
- `linear`: displayed in the same order defined in the image array,
  I'm unsure how glob pattern should be handled...
  Perhaps selected alpha-numerically or fallback to random/unique?
 
Once, the last image has been reached, simply repeat.

### Reason

The key element here for me is the `unique` parameter.
I have a limited selection of images set on the `editor` property, and maybe 3-4 split editor groups at a time.
There are always duplicate images between these splits and it would be nice to have some extra control over the order in which they are selected.

**Comment by Katsute** [comment]
The repeating backgrounds was actually a bug introduced in 2.1.0 and is fixed in #67.

The default behavior is non-repeating randoms. True randoms and linear orders will not be added because it would add additional complexity to the extension and not many users are likely to use these other options.
