### ISSUE TITLE
Letters and images become more transparent when you change the background opacity value

### ISSUE THREAD

**Issue by mijaelrev** [KatsuteDev/Background#75]
### Feature

New opacity options for both letters and images

### Reason

By changing the opacity of the backgrounds, my code letters also become more transparent, and images are no exception. I wish there was an option to prevent the above from happening as it makes it harder to visualize the job.
![image](https://user-images.githubusercontent.com/74110215/206866801-7eb0d0eb-5fac-4f3a-a346-7bd1e1f7b3fc.png)
![image](https://user-images.githubusercontent.com/74110215/206866991-2e0be9f5-d0a9-4116-9cc9-867d49b74f63.png)

**Comment by Katsute** [comment]
Use the `renderContentAboveBackground` option in the extension settings then reinstall

**Comment by mijaelrev** [comment]
the letters still become transparent when changing the opacity of the Background, don't you have an option for this?
![image](https://user-images.githubusercontent.com/74110215/207114215-a1981fe3-3fc1-458d-91a3-597619d57fdd.png)

**Comment by Katsute** [comment]
Unfortunately there is no possible way to fix the text opacity due to the limitations of css and the complexity of the VSCode UI.

Most VSCode background extensions (including this one) rely on the use of pseudo `::before` and `::after` css properties to overlay the background image above content to give the illusion of it being a background image. This means that:

* Background image will never be covered by other elements' backgrounds
* Opacity can be changed for background image
* Consequently, background image 'covers' content (as described above), causing to it appear opaque

We can not simply switch to using the `background-image` property for two reasons:

* VSCode sets background colors for nearly _all_ UI elements, so the background image is covered in all cases
* It is not possible to set the opacity of `background-image`

This issue will be closed as a 'won't fix' since css limitations make it impossible to fix this issue.
